<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit696897f22a146568eb39e9dfa9321ef4
{
    public static $prefixLengthsPsr4 = array (
        'a' => 
        array (
            'apimatic\\jsonmapper\\' => 20,
        ),
        'S' => 
        array (
            'Square\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'apimatic\\jsonmapper\\' => 
        array (
            0 => __DIR__ . '/..' . '/apimatic/jsonmapper/src',
        ),
        'Square\\' => 
        array (
            0 => __DIR__ . '/..' . '/square/square/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'U' => 
        array (
            'Unirest\\' => 
            array (
                0 => __DIR__ . '/..' . '/apimatic/unirest-php/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit696897f22a146568eb39e9dfa9321ef4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit696897f22a146568eb39e9dfa9321ef4::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit696897f22a146568eb39e9dfa9321ef4::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
